//
//  OpenID4VPMocks.generated.swift
//  OpenID4VP
//
//  Generated by Mockingbird v0.20.0.
//  DO NOT EDIT
//

// swiftlint:disable all

@testable import Mockingbird
@testable import OpenID4VP
import Foundation
import Sextant
import Swift
import os

// No mocks used in 'OpenID4VPTests'. Mockingbird is configured to only generate mocks for types
// that are explicitly initialized in your tests with `mock(SomeType.self)`. For more information,
// see 'Thunk Pruning' in the README.
