//
//  SiopOpenID4VPMocks.generated.swift
//  SiopOpenID4VP
//
//  Generated by Mockingbird v0.20.0.
//  DO NOT EDIT
//

// swiftlint:disable all

@_exported import PresentationExchange
@testable import Mockingbird
@testable import SiopOpenID4VP
import Foundation
import PresentationExchange
import Swift
import os

// No mocks used in 'SiopOpenID4VPTests'. Mockingbird is configured to only generate mocks for types
// that are explicitly initialized in your tests with `mock(SomeType.self)`. For more information,
// see 'Thunk Pruning' in the README.
