# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  
  desc "Code coverage"
  lane :code_coverage do
    tests
    xcov(
    scheme: "SiopOpenID4VP",
    output_directory: "xcov_output",
    is_swift_package: true
  )
  end

  desc "Runs unit tests"
  lane :tests do
    params = {
      package_path: '.',
      scheme: 'SiopOpenID4VP',
      devices: ['iPhone 14'], 
      result_bundle: true
    }

    if ENV['CI'] 
      params[:xcargs] = "-skipPackagePluginValidation"
    end

    run_tests(params)
  end

  desc "Builds the package"
  lane :just_build do
    xcodebuild(
      scheme: "SiopOpenID4VP",
      destination: "platform=iOS Simulator,OS=16.2,name=iPhone 8",
      xcargs: "-skipPackagePluginValidation"
    )
  end

  before_all do
    FileUtils.remove_dir '../xcov_output', true
  end

end
