# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Fix lint issues"
  lane :lint_fix do
    sh "swiftlint lint --fix --config ../.swiftlint.yml --quiet ../"
  end
  
  desc "Code coverage"
  lane :code_coverage do
    
    # You can convert the generated report to JSON using the following command:
    # xcrun xccov view xcov_output/xccovreport-0.xccovreport --json
    
    params = {
      package_path: '.',
      scheme: 'OpenID4VP',
      devices: ['iPhone 16'], 
      output_directory: "xcov_output",
      result_bundle: true
    }

    if ENV['CI'] 
      params[:xcargs] = "-skipPackagePluginValidation"
    end

    run_tests(params)

    xcov(
      scheme: "OpenID4VP",
      output_directory: "xcov_output",
      is_swift_package: true,
      minimum_coverage_percentage: 60.0
    )
    if ENV['CI'] != 'true'
      sh 'open ../xcov_output/index.html'
    end
  end

  desc "Runs unit tests"
  lane :tests do
    params = {
      package_path: '.',
      scheme: 'OpenID4VP',
      devices: ['iPhone 16'], 
      result_bundle: true
    }

    run_tests(params)
  end

  desc "Builds the package"
  lane :just_build do
    xcodebuild(
      scheme: "OpenID4VP",
      destination: "platform=iOS Simulator,OS=16.2,name=iPhone 8",
      xcargs: "-skipPackagePluginValidation -disableAutomaticPackageResolution"
    )
  end

  before_all do
    FileUtils.remove_dir '../xcov_output', true
  end

end
